name: Deployer

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
        composer install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        files: |
          **/*
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
