name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer:v2

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Node dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        files: |
          **/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
